"""Add kit assembly tables

Revision ID: 4779daac091a
Revises: 82e4a8e030c3
Create Date: 2025-12-28 20:55:11.794798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4779daac091a'
down_revision = '82e4a8e030c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
