"""Initial schema

Revision ID: 82e4a8e030c3
Revises: 
Create Date: 2025-12-28 18:14:23.333708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e4a8e030c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'WAREHOUSE_STAFF', 'PRODUCTION_STAFF', 'DISTRIBUTION_COORDINATOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('distributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('distribution_date', sa.DateTime(), nullable=False),
    sa.Column('distribution_type', sa.Enum('WEEKLY_PACKAGE', 'CRISIS_AID', 'SCHOOL_DELIVERY', 'BOARDING_HOME', 'LARGE_AID_DROP', 'OTHER', name='distributiontype'), nullable=False),
    sa.Column('items_distributed', sa.JSON(), nullable=False),
    sa.Column('recipient_info', sa.Text(), nullable=True),
    sa.Column('distributed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['distributed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distributions_distribution_date'), 'distributions', ['distribution_date'], unique=False)
    op.create_index(op.f('ix_distributions_distribution_type'), 'distributions', ['distribution_type'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('RAW_MATERIAL', 'IN_HOUSE_PRODUCT', 'PURCHASED_ITEM', 'ASSEMBLED_KIT', name='itemcategory'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('current_stock_level', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum_stock_level', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_index(op.f('ix_items_sku'), 'items', ['sku'], unique=True)
    op.create_table('purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('items_purchased', sa.JSON(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('received_by_user_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_purchase_date'), 'purchases', ['purchase_date'], unique=False)
    op.create_table('assemblies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assembly_date', sa.DateTime(), nullable=False),
    sa.Column('kit_type_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity_assembled', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('component_items', sa.JSON(), nullable=False),
    sa.Column('assembled_by_user_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assembled_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kit_type_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assemblies_assembly_date'), 'assemblies', ['assembly_date'], unique=False)
    op.create_index(op.f('ix_assemblies_kit_type_item_id'), 'assemblies', ['kit_type_item_id'], unique=False)
    op.create_table('productions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('production_date', sa.DateTime(), nullable=False),
    sa.Column('produced_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity_produced', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('raw_materials_used', sa.JSON(), nullable=True),
    sa.Column('produced_by_user_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produced_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['produced_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productions_produced_item_id'), 'productions', ['produced_item_id'], unique=False)
    op.create_index(op.f('ix_productions_production_date'), 'productions', ['production_date'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('IN', 'OUT', 'ADJUSTMENT', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference_type', sa.Enum('PRODUCTION', 'PURCHASE', 'ASSEMBLY', 'DISTRIBUTION', 'ADJUSTMENT', name='referencetype'), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_item_id'), 'stock_movements', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_reference_id'), 'stock_movements', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_reference_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_item_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_created_at'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_productions_production_date'), table_name='productions')
    op.drop_index(op.f('ix_productions_produced_item_id'), table_name='productions')
    op.drop_table('productions')
    op.drop_index(op.f('ix_assemblies_kit_type_item_id'), table_name='assemblies')
    op.drop_index(op.f('ix_assemblies_assembly_date'), table_name='assemblies')
    op.drop_table('assemblies')
    op.drop_index(op.f('ix_purchases_purchase_date'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_items_sku'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_distributions_distribution_type'), table_name='distributions')
    op.drop_index(op.f('ix_distributions_distribution_date'), table_name='distributions')
    op.drop_table('distributions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('categories')
    # ### end Alembic commands ###
