"""Add kit_templates table for sophisticated kit assembly

Revision ID: fdddbbb2159b
Revises: 82e4a8e030c3
Create Date: 2025-12-28 21:02:56.403644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdddbbb2159b'
down_revision = '82e4a8e030c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
